common: &COMMON
  adapter: postgresql
  username: postgres

development:
  <<: *COMMON
  database: security_development

test:
  <<: *COMMON
  database: security_test

production:
  adapter: postgresql
  username: security_user_1aaBB
  database: security_production
  password: 0hyouwi5h!w4aj0king
